FROM debian:12-slim

RUN set -eux; \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends squid; \
    rm -rf /var/lib/apt/lists/*

COPY ./squid.conf /etc/squid/conf.d/local.conf
COPY ./entrypoint.sh /entrypoint.sh

CMD [ "/entrypoint.sh", "squid"]
