FROM debian:11-slim

RUN set -eux; \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends squid apache2-utils netcat; \
    rm -rf /var/lib/apt/lists/*

COPY ./squid.conf /etc/squid/conf.d/local.conf

CMD [ "squid", "-N" ]
